spring.application.name: service-provider
server.port: 7999
spring.main.allow-bean-definition-overriding: true

  # Dubbo Application
  # The default value of dubbo.application.name is ${spring.application.name}
  # dubbo.application.name: ${spring.application.name}

# 扫描dubbo服务(@Service.. @Reference..)
dubbo.scan.basePackages: com.demo.dubboservice.service.impl

# 通信协议
dubbo.protocol.id :  dubbo
dubbo.protocol.name :  dubbo
dubbo.protocol.port :  20882

# 注册中心
dubbo.registry.id :  dubboRegistry
dubbo.registry.timeout: 5000
dubbo.registry.address: zookeeper://${zk.host}:${zk.port}
# Dubbo 支持 zkclient 和 curator 两种 Zookeeper 客户端实现：在2.7.x的版本中已经移除了zkclient的实现,如果要使用zkclient客户端,需要自行拓展
dubbo.registry.client: curator
# 元数据地址
dubbo.metadata-report.address: zookeeper://${zk.host}:${zk.port}